import os

CLOUD_NAME = os.getenv("CLOUDINARY_NAME")
API_KEY = os.getenv("CLOUDINARY_API_KEY")
API_SECRET = os.getenv("CLOUDINARY_API_SECRET")
CLOUD_URL = os.getenv("CLOUDINARY_URL")


__all__ = ("CLOUD_NAME", "API_KEY", "API_SECRET", "CLOUD_URL")
