import os

BACKEND_BASE_URL = os.getenv("BACKEND_BASE_URL")
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL")
APP_DOMAIN = os.getenv("APP_DOMAIN")


__all__ = ("FRONTEND_BASE_URL", "BACKEND_BASE_URL", "APP_DOMAIN")
